### ISSUE TITLE
Hawkeye synergy bug

### ISSUE THREAD

**Issue by XxLMDxX** [tyejae/msf.gg.public#220]
When having Ant-Man and Hawkeye in the same team, it shows synergy between them, when Ant-Man's passive should only work with Wasp

**Comment by tyejae** [comment]
@XxLMDxX So the game isn't very informative. You're getting that synergy because AntMan has a percentage chance to assist Hero allies. And Hawkeye is a hero ally. You can see in game he also gets the same synergy

![image](https://user-images.githubusercontent.com/6165105/90136899-b21f1300-dd29-11ea-9b8d-916565377bf3.png)
