### ISSUE TITLE
Missing SBC’s

### ISSUE THREAD

**Issue by Stampede33** [tyejae/msf.gg.public#223]
Have been saving around 400 SBCs for Maw to go from G12 to G13 but as of today all but 60 have disappeared. Including ones I just earned from the recent event. Not ok to just have items go missing from inventory after saving for so long

**Comment by Mike-T-Mitchell** [comment]
Hey @Stampede33, wow, that really stinks! I hope you've managed to get this taken care of in the 25 days since you posted this comment! Just in case you're still looking for a resolution to this problem, however:

You've posted this comment to the "issues" board of the MSF.gg web application, which is built and maintained by people whom are _not_ affiliated with Scopely in any way, and their only affiliation with "Marvel Strike Force" is that they play and enjoy the game! Therefore, the devs of the msf.gg web app did not cause this issue for you, nor is it in their power to resolve it.

You should reach out to the MSF dev team at Scopely by going to https://www.marvelstrikeforce.com/en/support and clicking the orange-colored "Contact Us" button (next to the search field on desktop devices, below it on mobile devices) and filing a ticket there. 

Good luck! 😀
