### ISSUE TITLE
Character Filter clean up

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#25]
- Type header should be renamed to Origin
- Origin header should be changed to something different. Location? Area?
- Mutant should be added to Bio, Tech, Skill, Mystic
- Asgard should be renamed to "Asgardian" and maybe moved to Team?
- Brotherhood should be a Team

**Comment by tyejae** [comment]
- Type header should be renamed to Origin
  - I think Type should be renamed to Trait
- Origin header should be changed to something different. Location? Area?
  - Leaving this because I renamed Type to Trait
- Mutant should be added to Bio, Tech, Skill, Mystic
  - Added!
- Asgard should be renamed to "Asgardian" and maybe moved to Team?
  - Left his for now. Asgard is an Origin according to FoxNext.
- Brotherhood should be a Team
  - Moved this to team!

**Comment by chronolinq** [comment]
Quick note about why I suggested Type should be renamed into Origin:

"Mystique’s appearance also heralds the arrival of the mutant **origin**"

That line indicates that Bio/Tech/Skill/Mystic/Mutant are classified as Origin Traits

Source: https://www.marvelstrikeforce.com/en/updates/developer-update-6
