### ISSUE TITLE
Assist/Counter polish

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#41]
- [x] Reduce the width of the icon to match the ability images below it. This way the text on the right will be aligned.
- [x] Also perhaps give it a dark gray background so that it looks more similar to the ability icons.
![image](https://user-images.githubusercontent.com/11431194/53291045-fdbeb500-3761-11e9-877b-9cb22c4fc1f6.png)
- [ ] Normalize piercing text to be like in-game descriptions. e.g. "Attack primary target for 144% damage + 35% Piercing" vs "Attack primary target for 144% damage. Gain 35% Piercing"
![image](https://user-images.githubusercontent.com/11431194/53291084-91908100-3762-11e9-9d29-6ec2b4efad23.png)
- [ ] When the percentage is 100%, the text reads differently. "Gain Deflect" vs "+100% chance to apply Deflect for 1 turn" (I personally like the "for 1 turn" but the in-game text usually leaves it out)
![image](https://user-images.githubusercontent.com/11431194/53291115-fba92600-3762-11e9-9027-18c50dd2b9d3.png)
![image](https://user-images.githubusercontent.com/11431194/53291124-0bc10580-3763-11e9-836c-d16e1057e5da.png)
![image](https://user-images.githubusercontent.com/11431194/53291128-1b404e80-3763-11e9-8744-4180a429773a.png)
- [ ] When it's a chance to apply/gain an effect, there's no preceding period
![image](https://user-images.githubusercontent.com/11431194/53291136-45920c00-3763-11e9-845e-1fe80613a5cd.png)

**Comment by chronolinq** [comment]
Example of the first and second items:

![image](https://user-images.githubusercontent.com/11431194/53435001-9e081a00-39ac-11e9-831d-244ee93c8682.png)

Styles used on the icon:
    font-size: 33px;
    background-color: #151515;
    width: 48px;
    height: 48px;
    line-height: 48px;
    text-align: center;

**Comment by tyejae** [comment]
I reduced the icon width and gave it a background color (and a border) like you suggested. I think that looks much better. Thank you.

For the rest of these requests. I'm literally generating this text from a set of binary checks that iterate over all of the characters and generates them on the fly. So that is the reason you see some of these small differences. Since I do not know if the logic will ALWAYS flow the same way (as FoxNext comes out with new characters), I found it more "future proof" to just put a period after each effect. So it may not read exactly as some of the basic abilities do. Hope that makes sense.
