### ISSUE TITLE
Missing assist and passive synergies

### ISSUE THREAD

**Issue by mcantrell** [tyejae/msf.gg.public#49]
![image](https://user-images.githubusercontent.com/20870/54044923-c9052180-4195-11e9-9f3b-0005b7af0127.png)

![image](https://user-images.githubusercontent.com/20870/54045267-c2c37500-4196-11e9-841a-b5a51dc5b3fd.png)

Seems like some ability assists and passives may be missing from the database.

**Comment by tyejae** [comment]
We only calculate _passive_ abilities that generate permanent boosts for the synergy calculations.

**Deadpool/Cable** ability synergy is on Cables Ultimate ability. Therefore not included because it's only available when he uses that one ability, not all the time.

**Groot/Rocket** ability synergy is on Rockets Special ability. Therefore, not included. However Groot's passive ability should be showing up. So I'll fix that with the issue.

**Comment by tyejae** [comment]
This is fixed and will be released later today.

![image](https://user-images.githubusercontent.com/6165105/55740907-ede0f480-59e0-11e9-8295-8f118adfa6be.png)

**Comment by varsas** [comment]
If only passives are meant to show then why is Rocket's 'Pretty Good Plan' now showing?
